### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Flashera** [JustGame/QuickChat#9]
You should implement some of these features:

http://massivecraft.com/massivechat

Also, it would be nice if you could format channels.

And also the ability to do /@ for ticket purposes.

**Comment by JayLegoMine14** [comment]
Thank you for the suggestions.

You can already format channels in the config file. Several example channels have been set up.

I believe the /@ command is already implemented, it is just not available to players.

**Comment by Flashera** [comment]
How can I make it available?

**Comment by Flashera** [comment]
/@ I mean

**Comment by Flashera** [comment]
Also, I don't understand how to format the channel.

**Comment by JayLegoMine14** [comment]
### Formatting Channels

(1)  Open the default QuickChat config.yml . You should then see something like this:

``` yml
broadcast: <&3Server&r>
private: LIGHT_PURPLE
ping:
  format: ITALIC
  sound: ORB_PICKUP
  volume: 60
  pitch: 0
channels:
  global:
    radius: -1
    color: WHITE
  local:
    radius: 100
    color: YELLOW
  staff:
    radius: -1
    color: AQUA
```

(2)  under `channels:` add a new channel following the example of the defualt channels, or duplicate one of the default channels and modify it. Like this:

``` yml
broadcast: <&3Server&r>
private: LIGHT_PURPLE
ping:
  format: ITALIC
  sound: ORB_PICKUP
  volume: 60
  pitch: 0
channels:
  global:
    radius: -1
    color: WHITE
  global:
    radius: -1
    color: WHITE
  local:
    radius: 100
    color: YELLOW
  staff:
    radius: -1
    color: AQUA
```

(3)  As you can see, I duplicated the global channel. Now edit the values to be anything you want. You can also change the values of any of the default channels if you so desire.  
**Note**: -1 radius means an infinite radius, and the `color:` must be a existing Bukkit/Spigot color.

``` yml
broadcast: <&3Server&r>
private: LIGHT_PURPLE
ping:
  format: ITALIC
  sound: ORB_PICKUP
  volume: 60
  pitch: 0
channels:
  global:
    radius: -1
    color: WHITE
  custom:
    radius: 500
    color: GREEN
  local:
    radius: 100
    color: YELLOW
  staff:
    radius: -1
    color: AQUA
```

**Important**: As you probably already know, spacing and line divisions are very important in yml files, so I recommend using a yml editor.
